apiVersion: v1
kind: Service
metadata:
  name: frontend-entrypoint
  namespace: dev
spec:
  selector:
    app: classicalslivefrontend
  ports:
    - name: development
      protocol: TCP
      port: 3001
      targetPort: 3000
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
